import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import {
  Container,
  Row,
  Col,
  Card,
  Button
} from "react-bootstrap";

function Reports() {

  const [users, setUsers] = useState([]);
  const [loans, setLoans] = useState([]);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {

    try {

      const userRes = await axios.get(
        "http://localhost:8080/rduserdata"
      );

      const loanRes = await axios.get(
        "http://localhost:8080/loan/all"
      );

      setUsers(userRes.data);
      setLoans(loanRes.data);

    } catch (err) {

      console.log(err);

    }
  };

  const totalBalance = users.reduce(
    (sum, user) => sum + Number(user.rdamt || 0),
    0
  );

  const approvedLoans = loans.filter(
    (l) => l.status === "APPROVED"
  ).length;

  const pendingLoans = loans.filter(
    (l) => l.status === "PENDING"
  ).length;



const exportPDF = () => {

  const doc = new jsPDF();
  doc.setFont("helvetica");
  doc.setFontSize(18);
  doc.text("RECURRING DEPOSIT SYSTEM REPORT", 20, 20);

  doc.setFontSize(12);

const date = new Date();

const today =
  String(date.getDate()).padStart(2, "0") +
  "/" +
  String(date.getMonth() + 1).padStart(2, "0") +
  "/" +
  date.getFullYear();

  doc.text(`Date : ${today}`, 20, 35);

  doc.line(20, 40, 190, 40);

  doc.text(`Total Users : ${users.length}`, 20, 55);

  doc.text(`Total RD Balance : Rs. ${totalBalance}`, 20, 65);

  doc.text(`Total Loans : ${loans.length}`, 20, 75);

  doc.text(`Approved Loans : ${approvedLoans}`, 20, 85);

  doc.text(`Pending Loans : ${pendingLoans}`, 20, 95);

  doc.line(20, 115, 190, 115);

  doc.text("Generated By :", 20, 130);
  doc.text("Recurring Deposit System", 20, 140);

  doc.save("RD_Report.pdf");
};

  return (
    <Container fluid className="mt-4">

      <h2 className="mb-4 text-primary">
        📊 Reports Dashboard
      </h2>

      <Row>

        <Col md={4}>
          <Card className="shadow border-0 mb-3">
            <Card.Body>
              <h5>Total Users</h5>
              <h2>{users.length}</h2>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow border-0 mb-3">
            <Card.Body>
              <h5>Total RD Balance</h5>
              <h2>₹{totalBalance}</h2>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow border-0 mb-3">
            <Card.Body>
              <h5>Total Loans</h5>
              <h2>{loans.length}</h2>
            </Card.Body>
          </Card>
        </Col>

      </Row>

      <Row>

        <Col md={4}>
          <Card className="shadow border-0 text-center bg-success text-white">
            <Card.Body>
              <h5>Approved Loans</h5>
              <h2>{approvedLoans}</h2>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow border-0 text-center bg-warning">
            <Card.Body>
              <h5>Pending Loans</h5>
              <h2>{pendingLoans}</h2>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      <div className="mt-4 text-center">

       <Button
        variant="danger"
        size="lg"
        onClick={exportPDF}
      >
        📄 Export PDF
    </Button>
      </div>
    </Container>
  );
}
export default Reports;